
- name: Reset the minion node
  shell: >
      kubeadm reset
  ignore_errors: yes

- name: Join master node
  shell: |
    systemctl daemon-reload
    service kubelet restart
    {{ hostvars.get(groups['master'][0]).get('kubeadm_join_command') }} --ignore-preflight-errors cri

